@ECHO OFF

IF NOT DEFINED IS_MINIMIZED SET IS_MINIMIZED=1 && START "" /min "remap.bat" %* && exit

SET /A REPEAT_INTERVAL = 7
SET /A KEEP_RUNNING = 1
SET /A REMAP_INTERVAL = 2

ECHO "STARTING REMAP"
TIMEOUT /t %REPEAT_INTERVAL% /nobreak > NUL
ECHO "REMAPPING..."
START map.ahk
ECHO "REMAPPED"
TIMEOUT /t REMAP_INTERVAL /nobreak > NUL
ECHO "ENTER"
START enter.ahk
TIMEOUT /t 1 /nobreak > NUL
ECHO "KILLING AHK"
TASKKILL /im AutoHotkey.exe > NUL
ECHO "KILLED AHK"

IF %KEEP_RUNNING% == 1 START /B remap.bat

EXIT
