@ECHO OFF

IF NOT DEFINED IS_MINIMIZED SET IS_MINIMIZED=1 && START "" /min "remap.bat" %* && exit

SET /A SECONDVALUE = 3
SET /A KEEPRUNNING = 1

ECHO "STARTING REMAP"
TIMEOUT /t %SECONDVALUE% /nobreak > NUL
ECHO "REMAPPING..."
START map.ahk
ECHO "REMAPPED"
TIMEOUT /t 2 /nobreak > NUL
ECHO "ENTER"
START enter.ahk
TIMEOUT /t 1 /nobreak > NUL
ECHO "KILLING AHK"
TASKKILL /im AutoHotkey.exe > NUL
ECHO "KILLED AHK"

IF %KEEPRUNNING% == 1 START /B remap.bat

EXIT